import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleApi,validateSnapshot} from '../server/api.mjs';
const origin='https://example.test';
function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../migrations/0001_accounts.sql',import.meta.url),'utf8'));const db={prepare(sql){return {bind(...args){return {first:async()=>sqlite.prepare(sql).get(...args)||null,run:async()=>sqlite.prepare(sql).run(...args),_run:()=>sqlite.prepare(sql).run(...args)};}};},async batch(statements){sqlite.exec('BEGIN');try{const values=statements.map(s=>s._run());sqlite.exec('COMMIT');return values;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};const env={DB:db,APP_ORIGIN:origin,GOOGLE_CLIENT_ID:'client',GOOGLE_CLIENT_SECRET:'secret'};return {sqlite,env};}
const req=(path,method='GET',body,headers={})=>new Request(origin+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
async function login(env,sub='one'){const start=await handleApi(req('/api/auth/google/start'),env);assert.equal(start.status,302);const target=new URL(start.headers.get('Location'));assert.equal(target.searchParams.get('code_challenge_method'),'S256');const state=target.searchParams.get('state'),nonce=target.searchParams.get('nonce');const callback=()=>handleApi(req(`/api/auth/google/callback?code=code&state=${state}`,'GET',null,{Cookie:`__Host-ab_oauth=${state}`}),env,{verifyGoogle:async()=>({sub,nonce,email:`${sub}@test.invalid`,email_verified:true,name:sub})});const result=await callback();assert.equal(result.headers.get('Location'),'/account/');const cookie=result.headers.getSetCookie().find(v=>v.startsWith('__Host-ab_session=')).split(';')[0];const session=await (await handleApi(req('/api/session','GET',null,{Cookie:cookie}),env)).json();return {cookie,session,callback,headers:{Cookie:cookie,Origin:origin,'X-CSRF-Token':session.csrfToken}};}
const doc=plan=>({version:2,entries:[],plan,profile:{categories:[],active:'gambling'}});
test('OAuth PKCE, nonce, secure cookie, state replay, sessions and security headers',async()=>{const {env,sqlite}=fixture();const user=await login(env);assert.equal(user.session.user.name,'one');assert.equal((await user.callback()).headers.get('Location'),'/account/?auth=failed');assert.equal(sqlite.prepare('SELECT count(*) n FROM sessions').get().n,1);const r=await handleApi(req('/api/snapshot','GET',null,user.headers),env);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.match(r.headers.get('X-Robots-Tag'),/noindex/);assert.deepEqual(await r.json(),{revision:0,data:doc('')});sqlite.close();});
test('separate accounts, atomic CAS concurrent writes, export and delete cascades',async()=>{const {env,sqlite}=fixture();const a=await login(env,'a'),b=await login(env,'b');const writes=await Promise.all(['first','second'].map(plan=>handleApi(req('/api/snapshot','PUT',{baseRevision:0,data:doc(plan)},a.headers),env)));assert.deepEqual(writes.map(r=>r.status).sort(),[200,409]);const conflict=await writes.find(r=>r.status===409).json();assert.equal(conflict.revision,1);assert.equal((await (await handleApi(req('/api/snapshot','GET',null,b.headers),env)).json()).data.plan,'');const exp=await handleApi(req('/api/export','GET',null,a.headers),env);assert.match(exp.headers.get('Content-Disposition'),/attachment/);assert.deepEqual(await exp.json(),{...conflict.data,remember:false});assert.equal((await handleApi(req('/api/account','DELETE',{confirmation:'DELETE'},a.headers),env)).status,200);assert.equal((await handleApi(req('/api/snapshot','GET',null,a.headers),env)).status,401);assert.equal(sqlite.prepare('SELECT count(*) n FROM users').get().n,1);assert.equal(sqlite.prepare('SELECT count(*) n FROM snapshots').get().n,1);sqlite.close();});
test('origin, CSRF, expiration, logout and missing config fail closed',async()=>{const {env,sqlite}=fixture();const a=await login(env);const body={baseRevision:0,data:doc('x')};assert.equal((await handleApi(req('/api/snapshot','PUT',body,{...a.headers,Origin:'https://evil.test'}),env)).status,403);assert.equal((await handleApi(req('/api/snapshot','PUT',body,{...a.headers,'X-CSRF-Token':'wrong'}),env)).status,403);sqlite.exec('UPDATE sessions SET expires_at=0');assert.equal((await handleApi(req('/api/snapshot','GET',null,a.headers),env)).status,401);const b=await login(env);assert.equal((await handleApi(req('/api/logout','POST',null,b.headers),env)).status,200);assert.equal((await handleApi(req('/api/snapshot','GET',null,b.headers),env)).status,401);assert.equal((await handleApi(req('/api/session'),{APP_ORIGIN:origin})).status,200);assert.equal((await handleApi(req('/api/auth/google/start'),{APP_ORIGIN:origin})).status,503);sqlite.close();});
test('strict document validation and body bounds',async()=>{const {env,sqlite}=fixture();const a=await login(env);const entry={date:'2026-02-30',urge:1,loneliness:1,social:1,sleep:1,financialStress:1,played:false,note:'',tags:[]};for(const data of [{...doc(''),entries:[entry]},doc('x'.repeat(2001)),{...doc(''),entries:[{...entry,date:'2026-01-01',urge:11}]},doc('x'.repeat(1048576))])assert.equal((await handleApi(req('/api/snapshot','PUT',{baseRevision:0,data},a.headers),env)).status,400);sqlite.close();});
test('OAuth rejects missing cookie, wrong nonce, unverified email and expired state',async()=>{for(const failure of ['cookie','nonce','email','expiry']){const {env,sqlite}=fixture();const start=await handleApi(req('/api/auth/google/start'),env);const u=new URL(start.headers.get('Location')),state=u.searchParams.get('state');if(failure==='expiry')sqlite.exec('UPDATE oauth_states SET expires_at=0');const r=await handleApi(req(`/api/auth/google/callback?state=${state}&code=x`,'GET',null,{Cookie:failure==='cookie'?'':`__Host-ab_oauth=${state}`}),env,{verifyGoogle:async()=>({sub:'x',nonce:failure==='nonce'?'wrong':u.searchParams.get('nonce'),email:'x@test.invalid',email_verified:failure!=='email'})});assert.equal(r.headers.get('Location'),'/account/?auth=failed');assert.equal(sqlite.prepare('SELECT count(*) n FROM sessions').get().n,0);sqlite.close();}});
test('login rate limit enforced and elapsed window resets',async()=>{const {env,sqlite}=fixture();for(let i=0;i<20;i++)assert.equal((await handleApi(req('/api/auth/google/start'),env)).status,302);assert.equal((await handleApi(req('/api/auth/google/start'),env)).status,429);sqlite.exec('UPDATE rate_limits SET expires_at=0');assert.equal((await handleApi(req('/api/auth/google/start'),env)).status,302);sqlite.close();});
test('simultaneous OAuth replay creates exactly one session',async()=>{const {env,sqlite}=fixture();const start=await handleApi(req('/api/auth/google/start'),env);const u=new URL(start.headers.get('Location')),state=u.searchParams.get('state');const cb=()=>handleApi(req(`/api/auth/google/callback?state=${state}&code=x`,'GET',null,{Cookie:`__Host-ab_oauth=${state}`}),env,{verifyGoogle:async()=>({sub:'race',nonce:u.searchParams.get('nonce'),email:'race@test.invalid',email_verified:true})});const results=await Promise.all([cb(),cb()]);assert.deepEqual(results.map(r=>r.headers.get('Location')).sort(),['/account/','/account/?auth=failed']);assert.equal(sqlite.prepare('SELECT count(*) n FROM sessions').get().n,1);sqlite.close();});
test('unknown routes and forged cookies cannot read journals; deletion requires literal confirmation',async()=>{const {env,sqlite}=fixture();const a=await login(env);assert.equal((await handleApi(req('/api/snapshot','GET',null,{Cookie:'__Host-ab_session='+'a'.repeat(64)}),env)).status,401);assert.equal((await handleApi(req('/api/account','DELETE',{confirmation:'yes'},a.headers),env)).status,400);assert.equal((await handleApi(req('/api/unknown','GET',null,a.headers),env)).status,404);assert.equal((await handleApi(new Request('https://evil.test/api/session'),env)).status,503);const r=await handleApi(req('/api/logout','POST',null,a.headers),env);assert.match(r.headers.get('Set-Cookie'),/Max-Age=0; HttpOnly; Secure; SameSite=Lax/);sqlite.close();});
test('v1 migrates to gambling once; old clients cannot overwrite v2 journeys',async()=>{const {env,sqlite}=fixture();const a=await login(env);const entry={date:'2026-01-01',urge:1,loneliness:1,social:1,sleep:1,financialStress:1,played:false,note:'legacy',tags:[]};const old={version:1,entries:[entry],plan:'shared'};const r=await handleApi(req('/api/snapshot','PUT',{baseRevision:0,data:old},a.headers),env);assert.equal(r.status,200);const upgraded=await r.json();assert.equal(upgraded.data.version,2);assert.equal(upgraded.data.entries[0].category,'gambling');assert.deepEqual(upgraded.data.profile.categories,['gambling']);const rejected=await handleApi(req('/api/snapshot','PUT',{baseRevision:1,data:old},a.headers),env);assert.equal(rejected.status,426);assert.equal((await rejected.json()).error,'client_upgrade_required');sqlite.close();});
test('journey profile sync and same-day different categories survive; duplicate and invalid categories fail',async()=>{const {env,sqlite}=fixture();const a=await login(env);const entry={date:'2026-01-01',category:'gambling',urge:1,loneliness:1,social:1,sleep:1,financialStress:1,played:false,note:'test',tags:[]};const alcohol={...entry,category:'alcohol',engaged:true};delete alcohol.played;const data={...doc('shared'),entries:[entry,alcohol],profile:{categories:['gambling','alcohol'],active:'alcohol'}};const good=await handleApi(req('/api/snapshot','PUT',{baseRevision:0,data},a.headers),env);assert.equal(good.status,200);assert.deepEqual((await good.json()).data,data.entries[0].category==='alcohol'?data:{...data,entries:[alcohol,entry]});for(const bad of [{...data,entries:[alcohol,alcohol]},{...data,profile:{categories:['invalid'],active:'alcohol'}},{...data,entries:[{...alcohol,engaged:undefined,played:true}]}])assert.equal((await handleApi(req('/api/snapshot','PUT',{baseRevision:1,data:bad},a.headers),env)).status,400);sqlite.close();});
test('legacy database reads/export normalize v2 without persisting or increasing revision',async()=>{const {env,sqlite}=fixture();const a=await login(env);const legacy={version:1,entries:[],plan:'old plan'};sqlite.prepare('UPDATE snapshots SET data=?,revision=7 WHERE user_id=?').run(JSON.stringify(legacy),a.session.user.id);const read=await (await handleApi(req('/api/snapshot','GET',null,a.headers),env)).json();assert.equal(read.revision,7);assert.equal(read.data.version,2);assert.deepEqual(read.data.profile.categories,['gambling']);const exported=await (await handleApi(req('/api/export','GET',null,a.headers),env)).json();assert.equal(exported.version,2);const stored=sqlite.prepare('SELECT revision,data FROM snapshots WHERE user_id=?').get(a.session.user.id);assert.equal(stored.revision,7);assert.equal(JSON.parse(stored.data).version,1);sqlite.close();});

test('active profile journey must belong to nonempty selection',()=>{assert.throws(()=>validateSnapshot({...doc(''),profile:{categories:['drugs'],active:'alcohol'}}),/profile/);assert.doesNotThrow(()=>validateSnapshot({...doc(''),profile:{categories:[],active:'general'}}));});
