'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
const source=fs.readFileSync(path.join(__dirname,'../web/public/preferences.js'),'utf8');
function mount({saved,dark=false,blocked=false}={}){const dom=new JSDOM('<html><head><meta name="theme-color"></head><body><select id="theme-choice"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select><p id="theme-status"></p></body></html>',{url:'https://example.com',runScripts:'outside-only'});const w=dom.window;let handler;const media={matches:dark,addEventListener(type,fn){handler=fn;}};w.matchMedia=()=>media;if(saved)w.localStorage.setItem('addiction-breaker:theme',saved);if(blocked)w.Storage.prototype.setItem=()=>{throw new Error('blocked');};w.eval(source);return {w,close:()=>w.close(),system(value){media.matches=value;handler();},choose(value){const e=w.document.getElementById('theme-choice');e.value=value;e.dispatchEvent(new w.Event('change'));}};}
test('system follows device changes while explicit theme stays fixed',()=>{const a=mount();try{assert.equal(a.w.document.documentElement.dataset.theme,'light');a.system(true);assert.equal(a.w.document.documentElement.dataset.theme,'dark');a.choose('light');a.system(true);assert.equal(a.w.document.documentElement.dataset.theme,'light');assert.equal(a.w.localStorage.getItem('addiction-breaker:theme'),'light');a.choose('system');assert.equal(a.w.document.documentElement.dataset.theme,'dark');}finally{a.close();}});
test('stored theme is restored; unknown stored value uses system without touching journal',()=>{const a=mount({saved:'dark'});try{assert.equal(a.w.document.documentElement.dataset.theme,'dark');assert.equal(a.w.localStorage.length,1);assert.equal(a.w.document.querySelector('meta').content,'#10191e');}finally{a.close();}const b=mount({saved:'invalid'});try{assert.equal(b.w.document.documentElement.dataset.theme,'light');assert.equal(b.w.document.getElementById('theme-choice').value,'system');}finally{b.close();}});
test('storage failure changes appearance without falsely claiming persistence',()=>{const a=mount({blocked:true});try{a.choose('dark');assert.equal(a.w.document.documentElement.dataset.theme,'dark');assert.match(a.w.document.getElementById('theme-status').textContent,/could not save/);}finally{a.close();}});
test('theme changes from another tab are reflected without reading journal contents',()=>{const a=mount();try{a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:'addiction-breaker:theme',newValue:'dark'}));assert.equal(a.w.document.documentElement.dataset.theme,'dark');a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:'addiction-breaker:v1',newValue:'private'}));assert.equal(a.w.document.documentElement.dataset.theme,'dark');}finally{a.close();}});
test('settings FAQ and roadmap have accessible structure and honest reporting links',()=>{const html=fs.readFileSync(path.join(__dirname,'../web/public/index.html'),'utf8');const d=new JSDOM(html);try{for(const id of ['settings','faq','roadmap']){const section=d.window.document.getElementById(id);assert.equal(section.className,'page');assert.ok(section.querySelector('h1'));}assert.match(d.window.document.getElementById('faq').textContent,/Reports are public/);assert.match(d.window.document.getElementById('roadmap').textContent,/not commitments/);assert.equal(d.window.document.querySelector('.urge-link').getAttribute('href'),'/pause/');assert.equal(d.window.document.querySelector('label[for="theme-choice"]').textContent.startsWith('Colour theme'),true);}finally{d.window.close();}});
